name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - run: npm ci

      - run: npm run test
        env:
          NODE_ENV: development
          DATABASE_URL: postgresql://default:1ebd9d49b83bd47e@localhost:5432/shortlink_db?schema=public
          JWT_EXPIRES_IN: 1d
          JWT_PRIVATE_KEY: 9ab0f1edab31a2a241cf1e3225d14931
          JWT_PUBLIC_KEY: 62a4861e75e1c95b39c0469e3d18e666
          API_DEVELOPMENT_URL: http://localhost:3333/api
          API_PRODUCTION_URL: https://shortlink-api.up.railway.app
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          REDIS_DB: 0
          REDIS_PASSWORD: 159753
          REDIS_USERNAME: default