version: '3.9'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker 
      - POSTGRESQL_PASSWORD=67a7e603-79db-41c3-8f1c-540cf59384c1
      - POSTGRESQL_DATABASE=user_db
